### ISSUE TITLE
deb package not properly installed

### ISSUE THREAD

**Issue by JohnFarl** [Ar-Ray-code/rpi-bullseye-ros2#13]
The deb package is not properly installed, I guess this is probably due to the installation of ros humble with previous method still present on device. 

How the properly uninstall ros humble installed with previous method to proceed with a clean installation of new deb version?

**Comment by Ar-Ray-code** [comment]
What is previous method ?

Regardless of methods are used, a clean install can be performed with the following command
This is because ROS is only installed in `/opt/ros/`.

```bash
sudo apt purge ros-humble* # If you were installing using dpkg, you can use
sudo  rm -rf /opt/ros # If you did the build yourself

**Comment by JohnFarl** [comment]
Ok thank you. Doesn't it have files also in other places?
