### ISSUE TITLE
ROS2 not found

### ISSUE THREAD

**Issue by vise-francesco** [Ar-Ray-code/rpi-bullseye-ros2#15]
Hi! I just tried installing the deb on git and everything was fine, but once run I got an error "ros2 command not found". Is there anything else to do to make it work?

**Comment by Ar-Ray-code** [comment]
What is your environment and installation procedure?

> Have you run `source /opt/ros/humble/setup.bash`?

**Comment by Ar-Ray-code** [comment]
I will try to install the following url.
https://s3.ap-northeast-1.wasabisys.com/download-raw/dpkg/ros2-desktop/debian/bullseye/ros-humble-desktop-0.3.1_arm64.deb

> May I ask you if it is possible to provide the foxy version too?

As you know, ros-foxy has reached EOL. so I do not support it before Humble.

**Comment by vise-francesco** [comment]
Thanks, now it's working
