### ISSUE TITLE
Raspberry Pi OS Bookworm compatibility

### ISSUE THREAD

**Issue by JohnFarl** [Ar-Ray-code/rpi-bullseye-ros2#16]
Now Raspberry Pi OS Bookworm has been released and has many significant changes as Wayland desktop environment.

There is an iron bookworm version in this repo, but considering this has been released many months before Raspberry Pi OS Bookworm release probably it used as reference a stock Debian (I guess).

Is this fully compatible also with Raspberry Pi OS Bookworm as well?

**Comment by Ar-Ray-code** [comment]
Yes, I actually tried rpi-bookworm right after its release and confirmed that it works except for Rviz and other GL systems.
However, please wait as it is broken and needs to be rebuilt.
For the most part, RaspberryPi OS is compatible with Debian OS and all dpkgs are built on qemu.

**Comment by JohnFarl** [comment]
Thanks for the info. I will wait the rebuilt version :)

**Comment by Ar-Ray-code** [comment]
I have updated.
Please read this installation.

https://github.com/Ar-Ray-code/rpi-bullseye-ros2#install-bookworm
