### ISSUE TITLE
libcurl.so.4 Raspbian Bullseye [Resolved]

### ISSUE THREAD

**Issue by rejero** [Ar-Ray-code/rpi-bullseye-ros2#18]
Hello, I faced this issue when I tried to colcon build cv_bridge, have installed libcurl4 so I'm not sure what I am missing here.

`/usr/bin/cmake: /opt/ros/humble/opt/libcurl_vendor/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)`

Solution: Found the solution and placing it here in case anyone needs, what I did was to make the default libcurl4 of ROS2 unavailable.

```
cd /opt/ros/humble/opt/libcurl_vendor/lib
sudo mv libcurl.so.4 libcurl.so.4.backup
sudo apt install --reinstall libcurl4
source /opt/ros/humble/setup.bash
```

And the issue went away

**Comment by Ar-Ray-code** [comment]
I too saw this problem from the beginning of the development, but left this one alone.
Thanks for the good solution. :+1:

**Comment by rejero** [comment]
Adding on, if you find the following the following error while compiling cv_bridge

`--- stderr: cv_bridge                                                                        
CMake Error at /usr/lib/aarch64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Could not find a package configuration file provided by "boost_python"
  (requested version 1.74.0) with any of the following names:

    boost_pythonConfig.cmake
    boost_python-config.cmake

  Add the installation prefix of "boost_python" to CMAKE_PREFIX_PATH or set
  "boost_python_DIR" to a directory containing one of the above files.  If
  "boost_python" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/aarch64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:258 (boost_find_component)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:448 (find_package)
  CMakeLists.txt:31 (find_package)


---
`

Just run
`sudo apt-get install libboost-python-dev`
