### ISSUE TITLE
colcon build problem

### ISSUE THREAD

**Issue by wyfwyfwyf1234567** [Ar-Ray-code/rpi-bullseye-ros2#25]
Hi! Thank you for sharing the files. I have installed the jazzy on raspberry pi 5 (bookworm) according to your instruction.  However, when I run the conmand 'colcon build', the following error occurs. Could you please help me fix the problem?
![59b33b8609b76ba1d0ec9987ff38570](https://github.com/user-attachments/assets/42d90a1c-a84b-4b9d-8107-2e3ae172fc97)

**Comment by Ar-Ray-code** [comment]
First, please tell me how to reproduction this.. (From ros2-jazzy installatin)

**Comment by wyfwyfwyf1234567** [comment]
The reproduction steps:
1.  wget https://s3.ap-northeast-1.wasabisys.com/download-raw/dpkg/ros2-desktop/debian/bookworm/ros-jazzy-desktop- 
     0.3.2_20240525_arm64.deb
2. sudo apt install ./ros-jazzy-desktop-0.3.2_20240525_arm64.deb
3. sudo pip install --break-system-packages vcstool colcon-common-extensions
4. source /opt/ros/jazzy/setup.bash
5. mkdir -p /ros2_ws/src
6. cd /ros2_ws
7. sudo git clone https://github.com/ros2/examples src/examples -b jazzy
8. sudo colcon build --symlink-install

**Comment by Ar-Ray-code** [comment]
Don't use colcon with `sudo`. You can build without admin privileges.

> [!TIP]
> Why is colcon installed with `sudo pip install colcon-common-extensions`?
> -> Because you need admin privileges to install under /usr/local/bin. You can use `which colcon` to check  where the `colcon` command is located.

**Comment by Ar-Ray-code** [comment]
However, I didn't get the same error log as yours, so I don't know if this will solve the problem.

**Comment by wyfwyfwyf1234567** [comment]
Thanks for your reply. it didn't work for me. May be I need to find other solution. thank you.

**Comment by Ar-Ray-code** [comment]
Maybe your ROS environment is broken...

Please show me the console result of `find /opt/ros/ -name rclcppConcifg.cmake`.

<br>

Expected result is `/opt/ros/jazzy/share/rclcpp/cmake/rclcppConfig.cmake`

**Comment by wyfwyfwyf1234567** [comment]
The console result shows nothing....
![e48406b72ecad7b64eea9054f4d8066](https://github.com/user-attachments/assets/20e1073a-b521-4ca6-8bd5-4cb75a01b00f)

**Comment by Ar-Ray-code** [comment]
It is likely that the dpkg is corrupt or has disappeared due to an unexpected error during installation (or subsequent operation).

In fact, I found `rclcppConfig.cmake` from `https://s3.ap-northeast-1.wasabisys.com/download-raw/dpkg/ros2-desktop/debian/bookworm/ros-jazzy-desktop-0.3.2_20240525_arm64.deb`. (same pkg from your procedure)

Reinstall it and check that there are no errors in its execution process.

```bash
~$ dpkg -c ros-jazzy-desktop-0.3.2_20240525_arm64.deb | grep rclcppConfig.cmake
-rw-r--r-- root/root      1379 2024-05-25 10:27 ./opt/ros/jazzy/share/rclcpp/cmake/rclcppConfig.cmake
-rw-r--r-- root/root      1336 2024-05-25 10:27 ./opt/ros/jazzy/share/test_rclcpp/cmake/test_rclcppConfig.cmake
```

**Comment by wyfwyfwyf1234567** [comment]
I reinstalled the bookworm on raspberry pi 5 and then reinstalled the `sudo apt install ./ros-jazzy-desktop-0.3.2_20240525_arm64.deb`. The colsole shows following result. (Notice)
![bb89070349209e5f79c95137e574174](https://github.com/user-attachments/assets/f158d86b-2c16-4f6a-a98c-bf966f65a18e)
Then I try to do `colcon build` according to the reproduction steps. The colsole shows the result:
![0c9b368d4b2ded104e08cae9d1e7f9a](https://github.com/user-attachments/assets/230b4b79-e1fc-489d-9237-3a186fc46acc)
Then I type `dpkg -c ros-jazzy-desktop-0.3.2_20240525_arm64.deb | grep ament_cmakeConfig.cmake`
the result is showed below.
![3667df60cc5147246afa3d40f32681e](https://github.com/user-attachments/assets/b2a2e663-5f88-47f0-9c4d-a786ffcfcde6)
The package is already included in the deb, but it cannot be found. This may be the problem. Could you please give me some suggestions? Thanks

**Comment by Ar-Ray-code** [comment]
Your log during installation look like same as mine...

If you can find the file with `find /opt/ros/ -name rclcppConcifg.cmake`, try deleting the build cache. (maybe you've already run)
```bash
rm -rf ~/ros2_ws/install ~/ros2_ws/build

# after removing the cache, run following
source /opt/ros/jazzy/setup.bash
colcon build
```

**Comment by wyfwyfwyf1234567** [comment]
I tried to build the official example in the official docker image, and the same error occurred. I tried the ros2 code provided by others, and it built normally. So I guess there is a problem in the official example. Thank you for your help.:>
