### ISSUE TITLE
Missing RViz rosbag rqt integration

### ISSUE THREAD

**Issue by JohnFarl** [Ar-Ray-code/rpi-bullseye-ros2#4]
I need to run ROS 2 Humble on Raspberry Pi OS bullseye ARM64 but the packages RViz, rosbag and rqt are missing. 
Is this caused by some compilation problem? How they could be included?

**Comment by Ar-Ray-code** [comment]
rosbag2 can be compiled, but rviz2 cannot be built, and rqt can be compiled but not run.

I have confirmed that rosbag2 works and will include it in the next release.

<br>

I am posting the following screenshots of the cause of the rviz2 and rqt errors. I have not found a solution at this time.

<br>

## Building Rviz2  (rviz_ogre_vendor)

![Screenshot from 2022-10-06 14-49-37](https://user-images.githubusercontent.com/67567093/194224978-985ad5ba-f7cd-455b-8ebb-3ec16e076c02.png)

## rqt_graph

![Screenshot from 2022-10-06 14-48-28](https://user-images.githubusercontent.com/67567093/194225057-4ba1d15b-5449-4de2-8297-6fbeb36a405e.png)

**Comment by JohnFarl** [comment]
@Ar-Ray-code The error seems related to missing X11 Ogre dependencies ...have you tried to install libxaw7-dev and libxt-dev?

**Comment by Ar-Ray-code** [comment]
rqt_graph is now working.

![image](https://user-images.githubusercontent.com/67567093/194460050-38e43f55-2347-4860-a22a-b8a42de30cc0.png)


I installed following packages additionally.

- pydot
- python3-pyqt5.qtsvg

**Comment by Ar-Ray-code** [comment]
debian base OS can`t install libxaw7-dev (but libxaw7 is available).

I think I have to build with libxaw from source code.
[libxaw (gitlab)](https://gitlab.freedesktop.org/xorg/lib/libxaw)

**Comment by JohnFarl** [comment]
I have find `libxaw7-dev` [here](http://ftp.de.debian.org/debian/pool/main/libx/libxaw/libxaw7-dev_1.0.13-1.1_arm64.deb)  searching on [debian.pkgs.org](https://debian.pkgs.org/11/debian-main-arm64/libxaw7-dev_1.0.13-1.1_arm64.deb.html)

**Comment by Ar-Ray-code** [comment]
Ah... It looks like libxaw7-dev can be installed on Raspbian-bullseye.
I'll check if it can be compiled on Raspbian 👀 

(How to install libxaw7-dev on debian:arm64 (docker) ?)

**Comment by Ar-Ray-code** [comment]
Rviz2 is now working.

I published [v0.2.0](https://github.com/Ar-Ray-code/rpi-bullseye-ros2/releases/tag/ros2-0.2.0), please use this

![rviz_rpi](https://user-images.githubusercontent.com/67567093/194687458-fa80582a-7832-43ec-81af-353475e16bb9.png)
