### ISSUE TITLE
Confusing version install readme

### ISSUE THREAD

**Issue by JohnFarl** [Ar-Ray-code/rpi-bullseye-ros2#6]
The readme on **Install** section shows the follow codelines to setup 

```
# default : (humble, arm7l)
curl -s https://raw.githubusercontent.com/Ar-Ray-code/rpi-bullseye-ros2/main/install.bash | bash
```

or

```
# default : (humble, aarch64)
wget https://raw.githubusercontent.com/Ar-Ray-code/rpi-bullseye-ros2/main/install.bash
bash install galactic aarch64 0.1.0 /opt/ros

```

this seems that first alternative install the 32 bit version of humble and second the 64 bit version of galactic but comment above says `humble, aarch64`

but in the first part of readme there is writtem 

| Version | aarch64 |
| --- | --- |
| humble | ✔ |
| galactic | |

This looks like confusing

Also in the installer
```
if [ -z "$TARGET_DISTRO" ];     then TARGET_DISTRO="humble";      fi
if [ -z "$ARCH" ];              then ARCH="armv7l";                 fi
if [ -z "$VERSION" ];           then VERSION="0.1.0";               fi
if [ -z "$ROS_INSTALL_DIR" ];   then ROS_INSTALL_DIR="/opt/ros";    fi
```

Thess lines
```
if [ -z "$ARCH" ];              then ARCH="armv7l";                 fi
if [ -z "$VERSION" ];           then VERSION="0.1.0";               fi
```

shouldn't be
```
if [ -z "$ARCH" ];              then ARCH="aarch64";                 fi
if [ -z "$VERSION" ];           then VERSION="0.2.0";               fi
```
considering that default target version is `humble`

???

**Comment by Ar-Ray-code** [comment]
I removed `curl -s` shortcut suggestions and set default version is [humble, aarch64, v0.2.0] .
