### ISSUE TITLE
QXcbConnection: XCB error launching rviz2 

### ISSUE THREAD

**Issue by JohnFarl** [Ar-Ray-code/rpi-bullseye-ros2#9]
`rviz2` on Raspberry Pi OS 64 bit bullseye after the default installation procedure crashes on launch with the following error:

`qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 192, resource id: 0, major code: 140 (Unknown), minor code: 20
`

I don't know if this may be related to an improper compilation of QT-related components as in a case described [here](https://stackoverflow.com/questions/45138522/xcb-error-148-qt-application-display-issues) but it seems a possible explaination. 

**UPDATE**

**The issue happen launching it using VNC when the attached display is in standby or turned off, otherwise it launchs correctly.** So probably the problem is caused by a change of behavior introduced in latest rviz itself that returns this error because it doesn't find any display active in this specific situation and error has nothing to do with your compilation procedure.

**Comment by Ar-Ray-code** [comment]
Yes, I know the similar problem when executing with X11-forwarding.🙃🙃🙃
I'm seeking a solution to this problem, too...

**Comment by Ar-Ray-code** [comment]
Currently only bookworm and Jazzy are maintained.
Since bookworm has confirmed that Rviz works by making Ubuntu24 the Client, I will not be able to address this issue 🙇
Please let me know if there are any more problems.
